on:
  schedule:
    - cron: '12 2 * * 6'
  workflow_dispatch:

name: 'Update versions'

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: node build.js
      - run: git config --global user.email "buildbot@frankl.in"
      - run: git config --global user.name "Build Bot"
      - run: git add lts.json
      - run: git add lts-current.json
      - run: git commit -m 'Update versions' && git push || true
