on:
  workflow_dispatch:

name: 'Update versions'

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: rm -f package-lock.json
      - run: node build.js
      - run: git config --global user.email "buildbot@frankl.in"
      - run: git config --global user.name "Build Bot"
      - run: git add lts.json
      - run: git add lts-current.json
      - run: git commit -m 'Update versions'
      - run: git push
